# VODIL EATS — Server va Tarmoq Sozlamalari
# Lokal Wi-Fi orqali sinash uchun: http://192.168.1.4:3000/api/v1/
# Real serverga (VPS) qo'yilganda server IP yoki domenni yozasiz (masalan: https://api.vodileats.uz/api/v1/)
SERVER_URL=http://192.168.1.4:3000/api/v1/

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
